feat: assignment completed
jhlfrfufyfn/multitreading_java pull request #1
Opened 2020-11-08 12:03 UTC by jhlfrfufyfn

2020-11-14 15:31 UTC, VeronikaYastr requested changes

2020-11-14 15:31 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +class SortByAscendingOrder implements Comparator<Integer> {
Лучше лямбда-выражения использовать, а не классы

2020-11-14 15:33 UTC, VeronikaYastr commented
Хм, а почему у вас с Егором абсолютно идентичный код, кто у кого списал?🙃

2020-11-16 11:11 UTC, jhlfrfufyfn commented
> Хм, а почему у вас с Егором абсолютно идентичный код, кто у кого списал?🙃

задание очень маленькое, шанс того, что у двух людей случайно будет написано очень похоже, выше, чем кажется(как в парадоксе дней рождения)

но если прям совсем идентичный, можно посмотреть например дату публикации

но опять же, в этом задании вообще нечего по-разному делать

2020-11-16 11:13 UTC, VeronikaYastr commented
Ну вы единственные, у кого так сильно совпало....

2020-11-16 11:29 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +class SortByAscendingOrder implements Comparator<Integer> {
done

2020-11-16 11:32 UTC, jhlfrfufyfn commented
> Ну вы единственные, у кого так сильно совпало....

я свой код пишу сам, больше мне нечего особо сказать на эту тему

2020-11-16 11:34 UTC, VeronikaYastr commented
Да я не сомневаюсь в твоих знаниях и умении писать код) просто смутило

2020-11-16 11:35 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +    List<Integer> getArray() {
геттеры и конструкторы как раз-таки лучше делать public

2020-11-18 14:18 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +    List<Integer> getArray() {
done

2020-12-25 10:47 UTC, merged